const NEXT_PUBLIC_PAYPAL_CLIENT_ID = process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID
const NEXT_PUBLIC_PAYPAL_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_PAYPAL_CLIENT_SECRET

const NEXT_PUBLIC_STRIPE_SECRET_KEY = process.env.NEXT_PUBLIC_STRIPE_SECRET_KEY
const NEXT_PUBLIC_STRIPE_WEBHOOK_ENDPOINT_SECRET =
  process.env.NEXT_PUBLIC_STRIPE_WEBHOOK_ENDPOINT_SECRET
const NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

export {
  NEXT_PUBLIC_PAYPAL_CLIENT_ID,
  NEXT_PUBLIC_PAYPAL_CLIENT_SECRET,
  NEXT_PUBLIC_STRIPE_SECRET_KEY,
  NEXT_PUBLIC_STRIPE_WEBHOOK_ENDPOINT_SECRET,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
}
